apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb-v67pb
  namespace: turnero-traumato
spec:
  clusterIP: 10.43.142.92
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: mongodb
  selector:
    app: mongodb
    release: mongodb-v67pb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
