{
 "title": "Orly",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Errores por Request URL",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT host, request, \"upstream_status\" FROM \"tail\" WHERE $timeFilter and (upstream_status=404 or upstream_status>=500)"
    }
   ]
  },
  {
   "title": "Upstream status codes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "2xx",
     "measurement": "tail",
     "query": "SELECT count(upstream_status) FROM \"tail\" WHERE upstream_status >= 200 and upstream_status <= 299 and $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "upstream_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "404",
     "measurement": "tail",
     "query": "SELECT count(upstream_status) FROM \"tail\" WHERE upstream_status = 404 and $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "upstream_status" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "5xx",
     "query": "SELECT count(upstream_status) FROM \"tail\" WHERE upstream_status >= 500 and $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Tiempos de respuesta upstream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT mean(\"upstream_response_time\") FROM \"tail\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "upstream_response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tiempo de respuesta por upstream promedio",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "measurement": "tail",
     "select": [
      [
       { "params": [ "upstream_host" ], "type": "field" }
      ],
      [
       { "params": [ "upstream_response_time" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errores por upstream",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "measurement": "tail",
     "query": "SELECT \"upstream_host\", \"upstream_status\" FROM \"tail\" WHERE $timeFilter and (upstream_status=404 or upstream_status>=500)",
     "select": [
      [
       { "params": [ "upstream_host" ], "type": "field" }
      ],
      [
       { "params": [ "upstream_status" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}