[package]
name = "test_server"
version = "0.1.0"
authors = ["Orlando Brea <orlando.brea@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
