---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  username: {{ randAlphaNum 6 | b64enc | quote }}
  password: {{ randAlphaNum 15 | b64enc | quote }}


---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-admin
type: Opaque
data:
  password: {{ .Values.global.postgres_admin_password | b64enc | quote }}


