---
apiVersion: v1
kind: Secret
metadata:
  name: backups
type: Opaque
data:
  server: {{ .Values.global.backup.server | b64enc | quote }}
  user: {{ .Values.global.backup.user | b64enc | quote }}
  password: {{ .Values.global.backup.password | b64enc | quote }}
  folder: {{ .Values.global.backup.folder | b64enc | quote }}


