---
apiVersion: v1
kind: Secret
metadata:
  name: backups
type: Opaque
data:
  server: {{ .Values.global.server | b64enc | quote }}
  user: {{ .Values.global.user | b64enc | quote }}
  password: {{ .Values.global.password | b64enc | quote }}
  folder: {{ .Values.global.folder | b64enc | quote }}


