---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: check-pvc-space-sa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: check-pvc-space-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: check-pvc-space-rb
  namespace: $NAMESPACE
subjects:
  - kind: ServiceAccount
    name: check-pvc-space-sa
    namespace: $NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: check-pvc-space-role

