  kind: StorageClass
  apiVersion: storage.k8s.io/v1
  metadata:
    name: csi-sc
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
  reclaimPolicy: Retain
  provisioner: csi.vsphere.vmware.com
  allowVolumeExpansion: true
  parameters:
    storagepolicyname: KuberneteStoragePolicy

