apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.3
          args:
            - --log.level=DEBUG
            #- --log.format=json
            - --api
            - --api.insecure
            - --entryPoints.traefik.address=:8100
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            
            - --entrypoints.tcpep.address=:8000
            - --entrypoints.udpep.address=:9000/udp
            - --entrypoints.hl7.address=:2575
            - --entrypoints.hl7.address=:2575/udp
            - --entrypoints.dicom.address=:2762
          
            - --providers.kubernetescrd
            - --providers.kubernetesingress=true
            - --api.debug=true
            #- --providers.kubernetescrd.namespaces=default,dcm4che
            - --serversTransport.insecureSkipVerify=true
            - --certificatesresolvers.default.acme.tlschallenge
            - --certificatesresolvers.default.acme.email=orlando.brea@gmail.com
            - --certificatesresolvers.default.acme.storage=acme.json
            # - --certificatesresolvers.default.acme.tlschallenge
            # - --certificatesresolvers.default.acme.email=foo@you.com
            # - --certificatesresolvers.default.acme.storage=acme.json
            # Please note that this is the staging Let's Encrypt server.
            # Once you get things working, you should remove that whole line altogether.
            #- --certificatesresolvers.default.acme.caserver=https://step-certificates/directory
            # - --tracing=true
            # - --tracing.zipkin=true
            # - --tracing.zipkin.httpEndpoint=http://192.168.0.8:9411/api/v2/spans
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443              
            - name: traefik-admin
              containerPort: 8100              
            - name: admin
              containerPort: 8080
            - name: tcpep
              containerPort: 8000
            - name: udpep
              containerPort: 9000
            - name: hl7
              containerPort: 2575
            - name: dicom
              containerPort: 2762

---
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - protocol: TCP
      port: 80
      name: web
      targetPort: 80
      nodePort: 30080
    - protocol: TCP
      port: 443
      name: websecure
      targetPort: 443
      nodePort: 30443      
    - protocol: TCP
      port: 8100
      name: traefik-admin
      targetPort: 8100
      nodePort: 30800      
    - protocol: TCP
      port: 8080
      name: admin
      targetPort: 8080
      nodePort: 30900
    - protocol: TCP
      port: 8000
      name: tcpep
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: traefikudp
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - protocol: UDP
      port: 9000
      name: udpep
      targetPort: 9000


---
apiVersion: v1
kind: Service
metadata:
  name: traefikhl7
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - protocol: TCP
      name: hl7
      port: 2575
      targetPort: 2575
      nodePort: 32575


---
apiVersion: v1
kind: Service
metadata:
  name: traefikhl7-udp
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:      
    - protocol: UDP
      name: hl7-udp
      port: 2575
      targetPort: 2575
      nodePort: 32576   

---
apiVersion: v1
kind: Service
metadata:
  name: traefikdicom
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:      
    - protocol: TCP      
      name: dicom
      port: 2762
      targetPort: 2762
      nodePort: 32762  
     
