kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: pvc-syspass-mysql
    namespace: $NAMESPACE
spec:
    storageClassName: csi-sc
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
