---
 - name: Create cron to free docker log space 
   hosts: kubernetes
   become: true 
   become_user: root 
   tasks:
    - name: Create cron
      ansible.builtin.cron:
        name: clear docker logs 
        hour: "01"
        minute: "0"
        weekday: "0"
        user: root 
        job: "find /var/lib/docker/containers/*/*-json.log | xargs -i{} truncate -s 0 {}"
    - name: Clean now 
      ansible.builtin.shell: 
        cmd: "find /var/lib/docker/containers/*/*-json.log | xargs -i{} truncate -s 0 {}"
    
       
    
