version: "3.1"
services: 
  reverse:
    image: nginx:1.19-alpine
    # image: haproxy:latest
    container_name: dcm4che_reverse
    ports:
      - 83:80
      - 443:443
      - 2762:2762
      - 2575:2575
      - 11112:11112
      - 1936:1936
    volumes: 
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/private