---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: guacamole-postgresql-pvc
spec:
  storageClassName: {{ $.Values.database.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storageSize }}
