---
apiVersion: v1
kind: Secret
metadata:
  name: guacamole-postgresql
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.database.username }}
  password: {{ .Values.database.password }} 
