---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  labels:
    app: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      name: guacamole
  template:
    metadata:
      labels:
        name: guacamole
        app: guacamole
    spec:
      containers:
        - name: guacamole
          image: "guacamole/guacamole:1.3.0"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DATABASE
              value: guacamole
            - name: POSTGRES_USER 
              valueFrom:
                secretKeyRef:
                  name: guacamole-postgresql
                  key: username                     
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: guacamole-postgresql
                  key: password                     
