apiVersion: v1
kind: Service
metadata:
  name: guacd
  labels:
    name: guacd  
    app: guacd  
spec:
  type: ClusterIP
  ports: 
    - name: web
      port: 4822
      targetPort: 4822
      protocol: TCP
  selector:
    app: guacd  

