---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: guacamole-compress
spec:
  compress: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: guacamole-addprefix
spec:
  addPrefix:
    prefix: /guacamole
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: guacamole
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Values.guacamole.domain }}`)
    kind: Rule
    services:
    - name: guacamole
      port: 8080
    middlewares:
    - name: guacamole-compress
    - name: guacamole-addprefix
#  tls:
#    hosts:
#      - sips-dashboard-app.andes.gob.ar
#    passthrough: false
#    options:
#      name: dashboard-tls-options

