---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turnero-app
  labels:
    app: turnero-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: turnero-app
  template:
    metadata:
      labels:
        name: turnero-app
        app: turnero-app
    spec:
      containers:
        - name: turnero-app
          image: "andesnqn/turnero-app:master"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
