apiVersion: v1
kind: Service
metadata:
  name: turnero-api
  labels:
    name: turnero-api
    app: turnero-api
spec:
  type: ClusterIP
  ports: 
    - name: web
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: turnero-api

