
# Tomando como ejemplo hospital.test.com para el nombre de dominio
# Se generan las siguientes rutas en el ingress
#   - keycloak-pacshospital.test.com
#   - visorhospital.test.com
#   - pacshospital.test.com
#   - console-pacshospital.test.com


# No cambiar el prefix
global:
  prefix: dcm4che
  domain: hpn.andes.gob.ar
  https_port: 30443
  ae_title: DCM4CHEE
  keycloak_user: admin
  keycloak_password: admin
  keycloak_regular_user: user
  keycloak_regular_password: user123
  andes_keycloak_secret: 
  postgres_admin_password: postgres

  persistence:
    enabled: true
    type: "PVC"
    storageClass: ""
  tls:
    custom_cert: true
    ca: "-empty-"
    
  backup:
    server: 192.168.68.1
    user: root
    password: root
    folder: /root/

